### PR TITLE
Support the Response format (Json mode) Provided by Mistral

### PR DESCRIPTION
**Pull request by Passant-Ihab**

### CODE REVIEW

**Comment by Skarzag** [comment]
Can't wait for this merge to be done ! 😄

**Comment by tghamm** [comment]
@Skarzag @Passant-Ihab sorry for the delay, I'll get this out tomorrow! 🙂

**Comment by Skarzag** [comment]
Hi @tghamm , will you get any time soon to do this ?

**Comment by tghamm** [comment]
@Skarzag my apologies, yes, I'll get it done this weekend. Thanks for your patience, life has gotten in the way the last couple of weeks unexpectedly.

**Comment by tghamm** [comment]
@Passant-Ihab thanks for the contribution and apologies for the delay, this has been incorporated and released.

**Comment by Skarzag** [comment]
@tghamm , no worries ! Do what you can do whenever you can !  Thanks to both of you anyway ;)

**Comment by Passant-Ihab** [comment]
@tghamm no worries! Thank you for processing it, really appreciated that will really help!

**Pull request merged**
